name: Run API tests 
description: Action to run api tests 

inputs: 
  api_base_url: 
    description: base url for api tests
    required: true
  
  workers:
    description: number of workers to run
    required: 1
    default: 1

runs:
  using: 'composite'
  steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Cache node modules
      uses: actions/cache@v4
      id: node-modules-cache
      with:
        path: |
          node_modules
        key: api-node-modules-${{ hashFiles('package-lock.json') }}
    
    - name: Install dependencies
      shell: bash
      run: npm ci
      if: steps.node-modules-cache.outputs.cache-hit != 'true'
      
    - name: Run API Playwright tests
      shell: bash
      run: npm run api
      env:
        API_BASE_URL: ${{ inputs.api_base_url }}
        WORKERS: ${{ inputs.workers }}

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: api-playwright-report
        path: playwright-report/
        retention-days: 3
