name: Playwright Tests
on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run_e2e_tests:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      WORKERS: 1
    steps:
        name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
        
        name: Run E2E Playwright tests
        uses: ./.github/actions/e2e-tests
        with:
          ui_home_base_url: ${{ secrets.UI_HOME_BASE_URL }}
          login_base_url: ${{ secrets.LOGIN_BASE_URL }}
          workers: ${{ env.WORKERS }}
          
  run_api_tests:
    name: Run API Tests
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      WORKERS: 1
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      
      - name: Run API tests
        uses: ./.github/actions/api-tests
        with:
          api_base_url: ${{ secrets.API_BASE_URL }}
          workers: ${{ env.WORKERS }}

    # - name: Deploy Playwright report to Github Pages
    #   uses: peaceiris/actions-gh-pages@v4
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_branch: gh-pages
    #     publish_dir: ./playwright-report
